### ISSUE TITLE
@EXPORT_OK does not always work

### ISSUE THREAD

**Issue by johndunlap** [Camelcade/Perl5-IDEA#1592]
I have been having problems getting my imports to work under normal conditions. Most of the imported util modules in our application do not correctly resolve. I've been able to coax it into working with 6-7 imports but, as yet, I haven't had much luck getting it to work with more than that. I've managed to reproduce this problem in a standalone project as follows:
![selection_005](https://user-images.githubusercontent.com/6990929/31462123-86d17704-ae99-11e7-8b19-cc4115256bb1.png)

# Util.pm
```
package TestExportOK::Util;
use strict;
use warnings FATAL => 'all';

use vars qw(@EXPORT_OK);
use Exporter qw(import);
@EXPORT_OK = qw(
    info
    debug
    trim
    ltrim
    rtrim
    ucwords
    is_equals
    is_empty
    is_number
    is_numeric
    is_blessed
    is_scalar
    is_isa
    is_can
    is_datetime
    is_array
    is_hash
    is_hashref
    is_arrayref
    is_undef
    is_in
    is_uuid
    is_iso8601
    is_sql92
    is_sql92_date
    is_integration_username
    is_phone_number
    unwrap
    superref
    assert_required
    assert_numeric
    assert_numeric_in_range
    assert_datetime
    assert_isa
    assert_hashref
    assert_arrayref
    assert_has_moose_role
    assert_i18n
    assert_in
    assert_can
    assert_equals
    assert_undef
    assert_defined
    assert_length
    assert_uuid
    assert_keys_in
    assert_iso8601
    assert_sql02
    assert_email
    array_search
    assert_empty
    optional_numeric
    optional_datetime
    optional_isa
    optional_hashref
    optional_in
    optional_arrayref
    optional_uuid
    create_phone_search
    create_ssn_search
    create_ein_search
    coalesce
    coalesce_undef
    replace_all
    parse_datetime_iso8601
    determine_transaction_entry_type
    extract_numeric
    extract_required
    extract_datetime
    extract_arrayref
    extract_hashref
    extract_uuid
    extract_iso8601
    extract_sql92
    capture_stack_trace
    create_query_arg_string
    random_alphanumeric_string
    sizeof
    is_email
    is_tax_id
    from_file
    from_file_binary
    throw_exception
    get_exception
    load_module_by_name
    is_filepath
    clean_currency_string
    shell
    to_file
);

sub info{}
sub debug{}
sub trim{}
sub ltrim{}
sub rtrim{}
sub ucwords{}
sub is_equals{}
sub is_empty{}
sub is_number{}
sub is_numeric{}
sub is_blessed{}
sub is_scalar{}
sub is_isa{}
sub is_can{}
sub is_datetime{}
sub is_array{}
sub is_hash{}
sub is_hashref{}
sub is_arrayref{}
sub is_undef{}
sub is_in{}
sub is_uuid{}
sub is_iso8601{}
sub is_sql92{}
sub is_sql92_date{}
sub is_integration_username{}
sub is_phone_number{}
sub unwrap{}
sub superref{}
sub assert_required{}
sub assert_numeric{}
sub assert_numeric_in_range{}
sub assert_datetime{}
sub assert_isa{}
sub assert_hashref{}
sub assert_arrayref{}
sub assert_has_moose_role{}
sub assert_i18n{}
sub assert_in{}
sub assert_can{}
sub assert_equals{}
sub assert_undef{}
sub assert_defined{}
sub assert_length{}
sub assert_uuid{}
sub assert_keys_in{}
sub assert_iso8601{}
sub assert_sql02{}
sub assert_email{}
sub array_search{}
sub assert_empty{}
sub optional_numeric{}
sub optional_datetime{}
sub optional_isa{}
sub optional_hashref{}
sub optional_in{}
sub optional_arrayref{}
sub optional_uuid{}
sub create_phone_search{}
sub create_ssn_search{}
sub create_ein_search{}
sub coalesce{}
sub coalesce_undef{}
sub replace_all{}
sub parse_datetime_iso8601{}
sub determine_transaction_entry_type{}
sub extract_numeric{}
sub extract_required{}
sub extract_datetime{}
sub extract_arrayref{}
sub extract_hashref{}
sub extract_uuid{}
sub extract_iso8601{}
sub extract_sql92{}
sub capture_stack_trace{}
sub create_query_arg_string{}
sub random_alphanumeric_string{}
sub sizeof{}
sub is_email{}
sub is_tax_id{}
sub from_file{}
sub from_file_binary{}
sub throw_exception{}
sub get_exception{}
sub load_module_by_name{}
sub is_filepath{}
sub clean_currency_string{}
sub shell{}
sub to_file{}

1;
```

# MyModule.pm
```
package TestExportOK::MyModule;
use strict;
use warnings FATAL => 'all';

use TestExportOK::Util qw(
    is_integration_username
    throw_exception
    optional_hashref
    optional_uuid
    optional_numeric
    assert_numeric_in_range
    assert_required
    assert_hashref
    assert_numeric
    assert_isa
    assert_in
    assert_datetime
    assert_uuid
    assert_arrayref
    assert_equals
    assert_iso8601
    assert_keys_in
    extract_numeric
    extract_required
    extract_hashref
    extract_uuid
    extract_iso8601
    unwrap
    trim
    is_number
    is_uuid
    is_hash
    is_in
    is_can
    is_undef
    is_isa
    is_equals
    coalesce
    coalesce_undef
    info
);

sub my_cool_method {
    my ($this, $value) = @_;

    assert_required($value);

    $this->do_something($value);
}

sub do_something {}

1;
```

# TestExportOK.pm
```
package TestExportOK;

use warnings FATAL => 'all';
use strict;

1;
```

When I open MyModule.pm in IDEA I see the following:
![selection_006](https://user-images.githubusercontent.com/6990929/31462226-fbe3777c-ae99-11e7-9e47-7c2febe68709.png)

**Comment by hurricup** [comment]
I guess that use `TextExport::Util` is unresolved too. Because libraries roots are not configured.

**Comment by johndunlap** [comment]
When you say "libraries roots", do you mean this?
![selection_007](https://user-images.githubusercontent.com/6990929/31681370-0bf54d7a-b345-11e7-9204-aeb6a952b26b.png)

**Comment by johndunlap** [comment]
![selection_008](https://user-images.githubusercontent.com/6990929/31681531-7fe9643c-b345-11e7-91e1-03fd37085f72.png)

**Comment by hurricup** [comment]
Feel free to build and test. Should work now. Thanks! Problem was that list of exported subs is big and being parsed other way for optimizations.

**Comment by johndunlap** [comment]
Unfortunately, this did not appear to fix the problem for me. I pulled the latest changes from git and then I ran the command
`./gradlew buildPlugin`

And then I updated the plugin to version 2017.3.2 by using the "Install from disk" option and I am still seeing this problem in my example project. Am I doing something wrong?

**Comment by hurricup** [comment]
Dam. That was not all. Try now :)

**Comment by johndunlap** [comment]
That worked! Thank you! :)

**Comment by hurricup** [comment]
Thank you!
